/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "H:\\Design\\Running\\Repositories\\FrontEnd\\VuePress\\normal\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-62161595",
    path: "/contact.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-62161595").then(next)
    },
  },
  {
    name: "v-51ce0b16",
    path: "/about.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-51ce0b16").then(next)
    },
  },
  {
    name: "v-5eb01e41",
    path: "/en/Mails/one.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5eb01e41").then(next)
    },
  },
  {
    name: "v-1c3e01f5",
    path: "/en/Mails/two.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1c3e01f5").then(next)
    },
  },
  {
    name: "v-4af31a5c",
    path: "/en/Mails/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4af31a5c").then(next)
    },
  },
  {
    path: "/en/Mails/index.html",
    redirect: "/en/Mails/"
  },
  {
    name: "v-177c5348",
    path: "/en/Guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-177c5348").then(next)
    },
  },
  {
    path: "/en/Guide/index.html",
    redirect: "/en/Guide/"
  },
  {
    name: "v-94152188",
    path: "/en/Office/Excel/FAQ/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-94152188").then(next)
    },
  },
  {
    path: "/en/Office/Excel/FAQ/index.html",
    redirect: "/en/Office/Excel/FAQ/"
  },
  {
    name: "v-dcd96482",
    path: "/en/Office/Excel/FAQ/four.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-dcd96482").then(next)
    },
  },
  {
    name: "v-a9aaa0ca",
    path: "/en/Office/Excel/FAQ/three.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a9aaa0ca").then(next)
    },
  },
  {
    name: "v-38d5dac6",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-38d5dac6").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-ebea79fc",
    path: "/en/Office/PPT/FAQ/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ebea79fc").then(next)
    },
  },
  {
    path: "/en/Office/PPT/FAQ/index.html",
    redirect: "/en/Office/PPT/FAQ/"
  },
  {
    name: "v-f78f828a",
    path: "/en/Office/PPT/FAQ/three.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f78f828a").then(next)
    },
  },
  {
    name: "v-ffd6740e",
    path: "/en/Office/PPT/FAQ/four.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ffd6740e").then(next)
    },
  },
  {
    name: "v-29baec3c",
    path: "/en/Office/Word/FAQ/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-29baec3c").then(next)
    },
  },
  {
    path: "/en/Office/Word/FAQ/index.html",
    redirect: "/en/Office/Word/FAQ/"
  },
  {
    name: "v-4c954100",
    path: "/en/Office/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4c954100").then(next)
    },
  },
  {
    path: "/en/Office/index.html",
    redirect: "/en/Office/"
  },
  {
    name: "v-7cda7522",
    path: "/en/Office/Word/FAQ/four.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7cda7522").then(next)
    },
  },
  {
    name: "v-3c88e961",
    path: "/en/Office/Word/FAQ/three.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3c88e961").then(next)
    },
  },
  {
    name: "v-c6d79856",
    path: "/en/Office/three.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c6d79856").then(next)
    },
  },
  {
    name: "v-761602bb",
    path: "/en/Office/four.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-761602bb").then(next)
    },
  },
  {
    name: "v-5831d189",
    path: "/en/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5831d189").then(next)
    },
  },
  {
    path: "/en/index.html",
    redirect: "/en/"
  },
  {
    name: "v-17d71a7c",
    path: "/zh/Guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-17d71a7c").then(next)
    },
  },
  {
    path: "/zh/Guide/index.html",
    redirect: "/zh/Guide/"
  },
  {
    name: "v-6e885e7c",
    path: "/zh/Mails/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6e885e7c").then(next)
    },
  },
  {
    path: "/zh/Mails/index.html",
    redirect: "/zh/Mails/"
  },
  {
    name: "v-db5a1caa",
    path: "/zh/Mails/two.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-db5a1caa").then(next)
    },
  },
  {
    name: "v-3a0414ec",
    path: "/zh/Notification/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3a0414ec").then(next)
    },
  },
  {
    path: "/zh/Notification/index.html",
    redirect: "/zh/Notification/"
  },
  {
    name: "v-0674eb66",
    path: "/zh/Office/678%20-%20%E5%89%AF%E6%9C%AC.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0674eb66").then(next)
    },
  },
  {
    path: "/zh/Office/678 - 副本.html",
    redirect: "/zh/Office/678%20-%20%E5%89%AF%E6%9C%AC.html"
  },
  {
    path: "/zh/Office/678 - 副本.html",
    redirect: "/zh/Office/678%20-%20%E5%89%AF%E6%9C%AC.html"
  },
  {
    name: "v-5675e412",
    path: "/zh/Mails/one.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5675e412").then(next)
    },
  },
  {
    name: "v-6c2b2d15",
    path: "/zh/Office/678.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6c2b2d15").then(next)
    },
  },
  {
    name: "v-0fa9db67",
    path: "/zh/Office/Excel/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0fa9db67").then(next)
    },
  },
  {
    path: "/zh/Office/Excel/index.html",
    redirect: "/zh/Office/Excel/"
  },
  {
    name: "v-27d5efe8",
    path: "/zh/Office/Excel/three.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-27d5efe8").then(next)
    },
  },
  {
    name: "v-ee2bdff0",
    path: "/zh/Office/PPT/567.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ee2bdff0").then(next)
    },
  },
  {
    name: "v-7ad84d68",
    path: "/zh/Office/PPT/678.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7ad84d68").then(next)
    },
  },
  {
    name: "v-767f9b98",
    path: "/zh/Office/Excel/four.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-767f9b98").then(next)
    },
  },
  {
    name: "v-1546c009",
    path: "/zh/Office/Word/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1546c009").then(next)
    },
  },
  {
    path: "/zh/Office/Word/index.html",
    redirect: "/zh/Office/Word/"
  },
  {
    name: "v-49025c26",
    path: "/zh/Office/PPT/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-49025c26").then(next)
    },
  },
  {
    path: "/zh/Office/PPT/index.html",
    redirect: "/zh/Office/PPT/"
  },
  {
    name: "v-636156b8",
    path: "/zh/Office/Word/three.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-636156b8").then(next)
    },
  },
  {
    name: "v-16116d82",
    path: "/zh/Office/Word/four.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-16116d82").then(next)
    },
  },
  {
    name: "v-5b519ddc",
    path: "/zh/Windows/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5b519ddc").then(next)
    },
  },
  {
    path: "/zh/Windows/index.html",
    redirect: "/zh/Windows/"
  },
  {
    name: "v-83f6552e",
    path: "/zh/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-83f6552e").then(next)
    },
  },
  {
    path: "/zh/index.html",
    redirect: "/zh/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]