/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/assets/img/hero.png",
        "heroText": "系统信息发布平台",
        "tagline": "天津三美电机",
        "actionText": "快速上手 →",
        "actionLink": "/zh/Guide/",
        "features": [
          {
            "title": "发布通知",
            "details": "此平台用于发布系统相关通知、联络。"
          },
          {
            "title": "办公软件操作",
            "details": "分享邮件、Office 办公软件常见操作方法，汇总操作技巧。"
          },
          {
            "title": "Windows 操作系统",
            "details": "操作系统常见问题、技巧总结。"
          }
        ],
        "footer": "Mitsumi | Copyright ©  管理部-企画课-系统"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-38d5dac6",
      "path": "/"
    },
    {
      "title": "关于我 1",
      "frontmatter": {},
      "regularPath": "/contact.html",
      "relativePath": "contact.md",
      "key": "v-62161595",
      "path": "/contact.html",
      "headers": [
        {
          "level": 2,
          "title": "关于我 1",
          "slug": "关于我-1"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1"
        },
        {
          "level": 3,
          "title": "1. 二级标题",
          "slug": "_1-二级标题"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-2"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-3"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-4"
        }
      ]
    },
    {
      "title": "关于我",
      "frontmatter": {
        "sidebar": true
      },
      "regularPath": "/about.html",
      "relativePath": "about.md",
      "key": "v-51ce0b16",
      "path": "/about.html",
      "headers": [
        {
          "level": 2,
          "title": "关于我",
          "slug": "关于我"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1"
        },
        {
          "level": 3,
          "title": "1. 二级标题",
          "slug": "_1-二级标题"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-2"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-3"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-4"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/en/Mails/",
      "relativePath": "en/Mails/README.md",
      "key": "v-4af31a5c",
      "path": "/en/Mails/"
    },
    {
      "frontmatter": {},
      "regularPath": "/en/Guide/",
      "relativePath": "en/Guide/README.md",
      "key": "v-177c5348",
      "path": "/en/Guide/"
    },
    {
      "title": "关于我 one",
      "frontmatter": {},
      "regularPath": "/en/Mails/one.html",
      "relativePath": "en/Mails/one.md",
      "key": "v-5eb01e41",
      "path": "/en/Mails/one.html",
      "headers": [
        {
          "level": 2,
          "title": "关于我 one",
          "slug": "关于我-one"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1"
        },
        {
          "level": 3,
          "title": "1. 二级标题",
          "slug": "_1-二级标题"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-2"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-3"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-4"
        }
      ]
    },
    {
      "title": "关于我 two",
      "frontmatter": {},
      "regularPath": "/en/Mails/two.html",
      "relativePath": "en/Mails/two.md",
      "key": "v-1c3e01f5",
      "path": "/en/Mails/two.html",
      "headers": [
        {
          "level": 2,
          "title": "关于我 two",
          "slug": "关于我-two"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1"
        },
        {
          "level": 3,
          "title": "1. 二级标题",
          "slug": "_1-二级标题"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-2"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-3"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-4"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/en/Office/Excel/FAQ/",
      "relativePath": "en/Office/Excel/FAQ/README.md",
      "key": "v-94152188",
      "path": "/en/Office/Excel/FAQ/"
    },
    {
      "frontmatter": {},
      "regularPath": "/en/Office/Excel/FAQ/four.html",
      "relativePath": "en/Office/Excel/FAQ/four.md",
      "key": "v-dcd96482",
      "path": "/en/Office/Excel/FAQ/four.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/en/Office/PPT/FAQ/",
      "relativePath": "en/Office/PPT/FAQ/README.md",
      "key": "v-ebea79fc",
      "path": "/en/Office/PPT/FAQ/"
    },
    {
      "title": "关于我 three",
      "frontmatter": {},
      "regularPath": "/en/Office/Excel/FAQ/three.html",
      "relativePath": "en/Office/Excel/FAQ/three.md",
      "key": "v-a9aaa0ca",
      "path": "/en/Office/Excel/FAQ/three.html",
      "headers": [
        {
          "level": 2,
          "title": "关于我 three",
          "slug": "关于我-three"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1"
        },
        {
          "level": 3,
          "title": "1. 二级标题",
          "slug": "_1-二级标题"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-2"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-3"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-4"
        }
      ]
    },
    {
      "title": "关于我 three",
      "frontmatter": {
        "0": "s",
        "1": "i",
        "2": "d",
        "3": "e",
        "4": "b",
        "5": "a",
        "6": "r",
        "7": ":",
        "8": "a",
        "9": "u",
        "10": "t",
        "11": "o"
      },
      "regularPath": "/en/Office/PPT/FAQ/three.html",
      "relativePath": "en/Office/PPT/FAQ/three.md",
      "key": "v-f78f828a",
      "path": "/en/Office/PPT/FAQ/three.html",
      "headers": [
        {
          "level": 2,
          "title": "关于我 three",
          "slug": "关于我-three"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1"
        },
        {
          "level": 3,
          "title": "1. 二级标题",
          "slug": "_1-二级标题"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-2"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-3"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-4"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/en/Office/PPT/FAQ/four.html",
      "relativePath": "en/Office/PPT/FAQ/four.md",
      "key": "v-ffd6740e",
      "path": "/en/Office/PPT/FAQ/four.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/en/Office/",
      "relativePath": "en/Office/README.md",
      "key": "v-4c954100",
      "path": "/en/Office/"
    },
    {
      "frontmatter": {},
      "regularPath": "/en/Office/Word/FAQ/four.html",
      "relativePath": "en/Office/Word/FAQ/four.md",
      "key": "v-7cda7522",
      "path": "/en/Office/Word/FAQ/four.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/en/Office/Word/FAQ/",
      "relativePath": "en/Office/Word/FAQ/README.md",
      "key": "v-29baec3c",
      "path": "/en/Office/Word/FAQ/"
    },
    {
      "title": "关于我 three",
      "frontmatter": {},
      "regularPath": "/en/Office/Word/FAQ/three.html",
      "relativePath": "en/Office/Word/FAQ/three.md",
      "key": "v-3c88e961",
      "path": "/en/Office/Word/FAQ/three.html",
      "headers": [
        {
          "level": 2,
          "title": "关于我 three",
          "slug": "关于我-three"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1"
        },
        {
          "level": 3,
          "title": "1. 二级标题",
          "slug": "_1-二级标题"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-2"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-3"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-4"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/en/Office/four.html",
      "relativePath": "en/Office/four.md",
      "key": "v-761602bb",
      "path": "/en/Office/four.html"
    },
    {
      "title": "关于我 three",
      "frontmatter": {},
      "regularPath": "/en/Office/three.html",
      "relativePath": "en/Office/three.md",
      "key": "v-c6d79856",
      "path": "/en/Office/three.html",
      "headers": [
        {
          "level": 2,
          "title": "关于我 three",
          "slug": "关于我-three"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1"
        },
        {
          "level": 3,
          "title": "1. 二级标题",
          "slug": "_1-二级标题"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-2"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-3"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-4"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/zh/Guide/",
      "relativePath": "zh/Guide/README.md",
      "key": "v-17d71a7c",
      "path": "/zh/Guide/"
    },
    {
      "frontmatter": {},
      "regularPath": "/zh/Mails/",
      "relativePath": "zh/Mails/README.md",
      "key": "v-6e885e7c",
      "path": "/zh/Mails/"
    },
    {
      "title": "关于我 one",
      "frontmatter": {},
      "regularPath": "/zh/Mails/one.html",
      "relativePath": "zh/Mails/one.md",
      "key": "v-5675e412",
      "path": "/zh/Mails/one.html",
      "headers": [
        {
          "level": 2,
          "title": "关于我 one",
          "slug": "关于我-one"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1"
        },
        {
          "level": 3,
          "title": "1. 二级标题",
          "slug": "_1-二级标题"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-2"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-3"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-4"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/assets/img/hero.png",
        "heroText": "Information Publishing Platform",
        "tagline": "Tianjin Mitsumi",
        "actionText": "快速上手 →",
        "actionLink": "/en/Guide/",
        "features": [
          {
            "title": "Notification Publishing",
            "details": "This platform is used for disseminating system-related notices and communications."
          },
          {
            "title": "Office Software Operations",
            "details": "Share common operation  for email and Office software, and compile operational techniques."
          },
          {
            "title": "Windows Operating System",
            "details": "Summarize common issues and tips related to the Windows operating system."
          }
        ],
        "footer": "Mitsumi | Copyright ©  Management Department - Planning Division - Systems"
      },
      "regularPath": "/en/",
      "relativePath": "en/README.md",
      "key": "v-5831d189",
      "path": "/en/"
    },
    {
      "title": "关于我 two",
      "frontmatter": {},
      "regularPath": "/zh/Mails/two.html",
      "relativePath": "zh/Mails/two.md",
      "key": "v-db5a1caa",
      "path": "/zh/Mails/two.html",
      "headers": [
        {
          "level": 2,
          "title": "关于我 two",
          "slug": "关于我-two"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1"
        },
        {
          "level": 3,
          "title": "1. 二级标题",
          "slug": "_1-二级标题"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-2"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-3"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-4"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/zh/Notification/",
      "relativePath": "zh/Notification/README.md",
      "key": "v-3a0414ec",
      "path": "/zh/Notification/"
    },
    {
      "title": "关于我 three",
      "frontmatter": {},
      "regularPath": "/zh/Office/678%20-%20%E5%89%AF%E6%9C%AC.html",
      "relativePath": "zh/Office/678 - 副本.md",
      "key": "v-0674eb66",
      "path": "/zh/Office/678%20-%20%E5%89%AF%E6%9C%AC.html",
      "headers": [
        {
          "level": 2,
          "title": "关于我 three",
          "slug": "关于我-three"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1"
        },
        {
          "level": 3,
          "title": "1. 二级标题",
          "slug": "_1-二级标题"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-2"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-3"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-4"
        }
      ]
    },
    {
      "title": "关于我 three",
      "frontmatter": {},
      "regularPath": "/zh/Office/Excel/",
      "relativePath": "zh/Office/Excel/README.md",
      "key": "v-0fa9db67",
      "path": "/zh/Office/Excel/",
      "headers": [
        {
          "level": 2,
          "title": "关于我 three",
          "slug": "关于我-three"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1"
        },
        {
          "level": 3,
          "title": "1. 二级标题",
          "slug": "_1-二级标题"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-2"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-3"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-4"
        }
      ]
    },
    {
      "title": "关于我 three",
      "frontmatter": {},
      "regularPath": "/zh/Office/678.html",
      "relativePath": "zh/Office/678.md",
      "key": "v-6c2b2d15",
      "path": "/zh/Office/678.html",
      "headers": [
        {
          "level": 2,
          "title": "关于我 three",
          "slug": "关于我-three"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1"
        },
        {
          "level": 3,
          "title": "1. 二级标题",
          "slug": "_1-二级标题"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-2"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-3"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-4"
        }
      ]
    },
    {
      "title": "关于我 three",
      "frontmatter": {},
      "regularPath": "/zh/Office/Excel/three.html",
      "relativePath": "zh/Office/Excel/three.md",
      "key": "v-27d5efe8",
      "path": "/zh/Office/Excel/three.html",
      "headers": [
        {
          "level": 2,
          "title": "关于我 three",
          "slug": "关于我-three"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1"
        },
        {
          "level": 3,
          "title": "1. 二级标题",
          "slug": "_1-二级标题"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-2"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-3"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-4"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/zh/Office/Excel/four.html",
      "relativePath": "zh/Office/Excel/four.md",
      "key": "v-767f9b98",
      "path": "/zh/Office/Excel/four.html"
    },
    {
      "title": "关于我 three",
      "frontmatter": {},
      "regularPath": "/zh/Office/PPT/567.html",
      "relativePath": "zh/Office/PPT/567.md",
      "key": "v-ee2bdff0",
      "path": "/zh/Office/PPT/567.html",
      "headers": [
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1"
        },
        {
          "level": 3,
          "title": "1. 二级标题",
          "slug": "_1-二级标题"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-2"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-3"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-4"
        }
      ]
    },
    {
      "title": "关于我 three",
      "frontmatter": {},
      "regularPath": "/zh/Office/PPT/678.html",
      "relativePath": "zh/Office/PPT/678.md",
      "key": "v-7ad84d68",
      "path": "/zh/Office/PPT/678.html",
      "headers": [
        {
          "level": 2,
          "title": "关于我 three",
          "slug": "关于我-three"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1"
        },
        {
          "level": 3,
          "title": "1. 二级标题",
          "slug": "_1-二级标题"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-2"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-3"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-4"
        }
      ]
    },
    {
      "title": "热爱生活，喜欢睡觉",
      "frontmatter": {},
      "regularPath": "/zh/Office/Word/",
      "relativePath": "zh/Office/Word/README.md",
      "key": "v-1546c009",
      "path": "/zh/Office/Word/",
      "headers": [
        {
          "level": 2,
          "title": "",
          "slug": ""
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1"
        },
        {
          "level": 3,
          "title": "1. 二级标题",
          "slug": "_1-二级标题"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-2"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-3"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-4"
        }
      ]
    },
    {
      "title": "关于我 three",
      "frontmatter": {},
      "regularPath": "/zh/Office/Word/three.html",
      "relativePath": "zh/Office/Word/three.md",
      "key": "v-636156b8",
      "path": "/zh/Office/Word/three.html",
      "headers": [
        {
          "level": 2,
          "title": "关于我 three",
          "slug": "关于我-three"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1"
        },
        {
          "level": 3,
          "title": "1. 二级标题",
          "slug": "_1-二级标题"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-2"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-3"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-4"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/zh/Office/Word/four.html",
      "relativePath": "zh/Office/Word/four.md",
      "key": "v-16116d82",
      "path": "/zh/Office/Word/four.html"
    },
    {
      "title": "热爱生活，喜欢睡觉",
      "frontmatter": {},
      "regularPath": "/zh/Windows/",
      "relativePath": "zh/Windows/README.md",
      "key": "v-5b519ddc",
      "path": "/zh/Windows/",
      "headers": [
        {
          "level": 2,
          "title": "",
          "slug": ""
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1"
        },
        {
          "level": 3,
          "title": "1. 二级标题",
          "slug": "_1-二级标题"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-2"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-3"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-4"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/zh/",
      "relativePath": "zh/README.md",
      "key": "v-83f6552e",
      "path": "/zh/"
    },
    {
      "frontmatter": {},
      "regularPath": "/zh/Office/PPT/",
      "relativePath": "zh/Office/PPT/README.md",
      "key": "v-49025c26",
      "path": "/zh/Office/PPT/"
    }
  ],
  "themeConfig": {
    "logo": "/assets/img/hero.png",
    "locales": {
      "/": {
        "selectText": "选择语言",
        "label": "简体中文",
        "ariaLabel": "Languages",
        "nav": [
          {
            "text": "指南",
            "link": "/zh/Guide/"
          },
          {
            "text": "通知",
            "link": "/zh/Notification/"
          },
          {
            "text": "邮件",
            "link": "/zh/Mails/"
          },
          {
            "text": "办公软件",
            "items": [
              {
                "text": "Excel",
                "link": "/zh/Office/Excel/"
              },
              {
                "text": "PowerPoint",
                "link": "/zh/Office/PPT/"
              },
              {
                "text": "Winword",
                "link": "/zh/Office/Word/"
              }
            ]
          },
          {
            "text": "操作系统",
            "link": "/zh/Windows/"
          }
        ],
        "sidebar": {
          "/zh/Office/Excel/": [
            "",
            "four",
            "three"
          ],
          "/zh/Office/PPT/": [
            "",
            "567",
            "678"
          ],
          "/zh/Office/Word/": [
            "",
            "four",
            "three"
          ],
          "/zh/Guide/": [
            ""
          ],
          "/zh/Notification/": [
            ""
          ],
          "/zh/Mails/": [
            "",
            "one",
            "two"
          ],
          "/zh/Windows/": [
            ""
          ]
        }
      },
      "/en/": {
        "selectText": "Languages",
        "label": "English",
        "ariaLabel": "Languages",
        "nav": [
          {
            "text": "Guide",
            "link": "/en/Guide/"
          },
          {
            "text": "Notification",
            "link": "/en/Notification/"
          },
          {
            "text": "GWS",
            "link": "/en/Mails/"
          },
          {
            "text": "Office",
            "items": [
              {
                "text": "Excel",
                "link": "/en/Office/Excel/"
              },
              {
                "text": "PowerPoint",
                "link": "/en/Office/PPT/"
              },
              {
                "text": "Winword",
                "link": "/en/Office/Word/"
              }
            ]
          },
          {
            "text": "Windows",
            "link": "/en/Windows/"
          }
        ],
        "sidebar": {
          "/en/Office/Excel/": [
            ""
          ],
          "/en/Office/PPT/": [
            ""
          ],
          "/en/Office/Word/": [
            ""
          ],
          "/en/Guide/": [
            ""
          ],
          "/en/Notification/": [
            ""
          ],
          "/en/Mails/": [
            "",
            "one",
            "two"
          ],
          "/en/Windows/": [
            ""
          ]
        }
      }
    }
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "title": "Mitsumi",
      "description": "信息发布平台",
      "path": "/"
    },
    "/en/": {
      "lang": "en-US",
      "title": "Mitsumi",
      "description": "information publishing platform",
      "path": "/en/"
    }
  }
}