/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "H:\\Design\\Running\\Repositories\\FrontEnd\\VuePress\\vuepress-theme-vdoing\\更新版本配置\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-7ab61a21",
    path: "/archives/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7ab61a21").then(next)
    },
  },
  {
    path: "/archives/index.html",
    redirect: "/archives/"
  },
  {
    path: "/@pages/archivesPage.html",
    redirect: "/archives/"
  },
  {
    name: "v-0c696781",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0c696781").then(next)
    },
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    path: "/@pages/categoriesPage.html",
    redirect: "/categories/"
  },
  {
    name: "v-a21c48be",
    path: "/tags/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a21c48be").then(next)
    },
  },
  {
    path: "/tags/index.html",
    redirect: "/tags/"
  },
  {
    path: "/@pages/tagsPage.html",
    redirect: "/tags/"
  },
  {
    name: "v-a6d8d532",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a6d8d532").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-465ca4f4",
    path: "/about.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-465ca4f4").then(next)
    },
  },
  {
    name: "v-4b1b2ed8",
    path: "/contact.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4b1b2ed8").then(next)
    },
  },
  {
    name: "v-703312dd",
    path: "/pages/024db4/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-703312dd").then(next)
    },
  },
  {
    path: "/pages/024db4/index.html",
    redirect: "/pages/024db4/"
  },
  {
    path: "/zh/Mails/",
    redirect: "/pages/024db4/"
  },
  {
    name: "v-1b30ee36",
    path: "/pages/8ad370/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1b30ee36").then(next)
    },
  },
  {
    path: "/pages/8ad370/index.html",
    redirect: "/pages/8ad370/"
  },
  {
    path: "/zh/Mails/one.html",
    redirect: "/pages/8ad370/"
  },
  {
    name: "v-4e825c2c",
    path: "/pages/f4e357/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4e825c2c").then(next)
    },
  },
  {
    path: "/pages/f4e357/index.html",
    redirect: "/pages/f4e357/"
  },
  {
    path: "/zh/Mails/two.html",
    redirect: "/pages/f4e357/"
  },
  {
    name: "v-6ab936f2",
    path: "/pages/769016/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6ab936f2").then(next)
    },
  },
  {
    path: "/pages/769016/index.html",
    redirect: "/pages/769016/"
  },
  {
    path: "/zh/Office/Excel/01.OKOKOK.html",
    redirect: "/pages/769016/"
  },
  {
    name: "v-32acd208",
    path: "/pages/228438/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-32acd208").then(next)
    },
  },
  {
    path: "/pages/228438/index.html",
    redirect: "/pages/228438/"
  },
  {
    path: "/zh/Office/Excel/",
    redirect: "/pages/228438/"
  },
  {
    name: "v-d8207c9e",
    path: "/pages/d6aa36/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d8207c9e").then(next)
    },
  },
  {
    path: "/pages/d6aa36/index.html",
    redirect: "/pages/d6aa36/"
  },
  {
    path: "/zh/Office/Word/01.OKOKOK.html",
    redirect: "/pages/d6aa36/"
  },
  {
    name: "v-6828eaea",
    path: "/pages/a0b332/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6828eaea").then(next)
    },
  },
  {
    path: "/pages/a0b332/index.html",
    redirect: "/pages/a0b332/"
  },
  {
    path: "/zh/Office/Word/",
    redirect: "/pages/a0b332/"
  },
  {
    name: "v-087cb0ce",
    path: "/pages/86df31/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-087cb0ce").then(next)
    },
  },
  {
    path: "/pages/86df31/index.html",
    redirect: "/pages/86df31/"
  },
  {
    path: "/zh/Office/ppt/",
    redirect: "/pages/86df31/"
  },
  {
    name: "v-aa3de784",
    path: "/pages/9e874c/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-aa3de784").then(next)
    },
  },
  {
    path: "/pages/9e874c/index.html",
    redirect: "/pages/9e874c/"
  },
  {
    path: "/zh/Office/ppt/测试文件名字.html",
    redirect: "/pages/9e874c/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]