/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "归档",
      "frontmatter": {
        "archivesPage": true,
        "title": "归档",
        "permalink": "/archives/",
        "article": false
      },
      "regularPath": "/@pages/archivesPage.html",
      "relativePath": "@pages/archivesPage.md",
      "key": "v-7ab61a21",
      "path": "/archives/"
    },
    {
      "title": "分类",
      "frontmatter": {
        "categoriesPage": true,
        "title": "分类",
        "permalink": "/categories/",
        "article": false
      },
      "regularPath": "/@pages/categoriesPage.html",
      "relativePath": "@pages/categoriesPage.md",
      "key": "v-0c696781",
      "path": "/categories/"
    },
    {
      "title": "标签",
      "frontmatter": {
        "tagsPage": true,
        "title": "标签",
        "permalink": "/tags/",
        "article": false
      },
      "regularPath": "/@pages/tagsPage.html",
      "relativePath": "@pages/tagsPage.md",
      "key": "v-a21c48be",
      "path": "/tags/"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/assets/img/hero.png",
        "heroText": "系统信息发布平台",
        "tagline": "天津三美电机有限公司",
        "actionText": "快速上手 →",
        "actionLink": "/about",
        "bannerBg": "none",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": {
          "MIT Licensed | Copyright © 2018-present Evan You": null
        },
        "postList": "simple",
        "hideRightBar": true
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-a6d8d532",
      "path": "/"
    },
    {
      "title": "关于我",
      "frontmatter": {
        "sidebar": true
      },
      "regularPath": "/about.html",
      "relativePath": "about.md",
      "key": "v-465ca4f4",
      "path": "/about.html",
      "headers": [
        {
          "level": 2,
          "title": "关于我",
          "slug": "关于我"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1"
        },
        {
          "level": 3,
          "title": "1. 二级标题",
          "slug": "_1-二级标题"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-2"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-3"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-4"
        }
      ]
    },
    {
      "title": "关于我 1",
      "frontmatter": {},
      "regularPath": "/contact.html",
      "relativePath": "contact.md",
      "key": "v-4b1b2ed8",
      "path": "/contact.html",
      "headers": [
        {
          "level": 2,
          "title": "关于我 1",
          "slug": "关于我-1"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1"
        },
        {
          "level": 3,
          "title": "1. 二级标题",
          "slug": "_1-二级标题"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-2"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-3"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-4"
        }
      ]
    },
    {
      "title": "README",
      "frontmatter": {
        "title": "README",
        "date": "2023-11-21T08:12:39.000Z",
        "permalink": "/pages/024db4/",
        "categories": [
          "zh",
          "Mails"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/zh/Mails/",
      "relativePath": "zh/Mails/README.md",
      "key": "v-703312dd",
      "path": "/pages/024db4/"
    },
    {
      "title": "one",
      "frontmatter": {
        "title": "one",
        "date": "2023-11-21T08:12:39.000Z",
        "permalink": "/pages/8ad370/",
        "categories": [
          "zh",
          "Mails"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/zh/Mails/one.html",
      "relativePath": "zh/Mails/one.md",
      "key": "v-1b30ee36",
      "path": "/pages/8ad370/",
      "headers": [
        {
          "level": 2,
          "title": "关于我 one",
          "slug": "关于我-one"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1"
        },
        {
          "level": 3,
          "title": "1. 二级标题",
          "slug": "_1-二级标题"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-2"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-3"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-4"
        }
      ]
    },
    {
      "title": "two",
      "frontmatter": {
        "title": "two",
        "date": "2023-11-21T08:12:39.000Z",
        "permalink": "/pages/f4e357/",
        "categories": [
          "zh",
          "Mails"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/zh/Mails/two.html",
      "relativePath": "zh/Mails/two.md",
      "key": "v-4e825c2c",
      "path": "/pages/f4e357/",
      "headers": [
        {
          "level": 2,
          "title": "关于我 two",
          "slug": "关于我-two"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1"
        },
        {
          "level": 3,
          "title": "1. 二级标题",
          "slug": "_1-二级标题"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-2"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-3"
        },
        {
          "level": 2,
          "title": "一级标题 1",
          "slug": "一级标题-1-4"
        }
      ]
    },
    {
      "title": "OKOKOK",
      "frontmatter": {
        "title": "OKOKOK",
        "date": "2023-11-21T15:59:30.000Z",
        "permalink": "/pages/769016/",
        "categories": [
          "zh",
          "Office",
          "Excel"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/zh/Office/Excel/01.OKOKOK.html",
      "relativePath": "zh/Office/Excel/01.OKOKOK.md",
      "key": "v-6ab936f2",
      "path": "/pages/769016/"
    },
    {
      "title": "README",
      "frontmatter": {
        "title": "README",
        "date": "2023-11-21T15:41:04.000Z",
        "permalink": "/pages/228438/",
        "categories": [
          "zh",
          "Office",
          "Excel"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/zh/Office/Excel/",
      "relativePath": "zh/Office/Excel/README.md",
      "key": "v-32acd208",
      "path": "/pages/228438/"
    },
    {
      "title": "OKOKOK",
      "frontmatter": {
        "title": "OKOKOK",
        "date": "2023-11-21T16:00:19.000Z",
        "permalink": "/pages/d6aa36/",
        "categories": [
          "zh",
          "Office",
          "Word"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/zh/Office/Word/01.OKOKOK.html",
      "relativePath": "zh/Office/Word/01.OKOKOK.md",
      "key": "v-d8207c9e",
      "path": "/pages/d6aa36/"
    },
    {
      "title": "README",
      "frontmatter": {
        "title": "README",
        "date": "2023-11-21T15:41:08.000Z",
        "permalink": "/pages/a0b332/",
        "categories": [
          "zh",
          "Office",
          "Word"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/zh/Office/Word/",
      "relativePath": "zh/Office/Word/README.md",
      "key": "v-6828eaea",
      "path": "/pages/a0b332/"
    },
    {
      "title": "README",
      "frontmatter": {
        "title": "README",
        "date": "2023-11-21T16:21:23.000Z",
        "permalink": "/pages/86df31/",
        "categories": [
          "zh",
          "Office",
          "ppt"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/zh/Office/ppt/",
      "relativePath": "zh/Office/ppt/README.md",
      "key": "v-087cb0ce",
      "path": "/pages/86df31/"
    },
    {
      "title": "测试文件名字",
      "frontmatter": {
        "title": "测试文件名字",
        "date": "2023-11-21T16:21:46.000Z",
        "permalink": "/pages/9e874c/",
        "categories": [
          "zh",
          "Office",
          "ppt"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/zh/Office/ppt/%E6%B5%8B%E8%AF%95%E6%96%87%E4%BB%B6%E5%90%8D%E5%AD%97.html",
      "relativePath": "zh/Office/ppt/测试文件名字.md",
      "key": "v-aa3de784",
      "path": "/pages/9e874c/"
    }
  ],
  "themeConfig": {
    "logo": "/assets/img/hero.png",
    "locales": {
      "/": {
        "selectText": "选择语言",
        "label": "简体中文",
        "ariaLabel": "Languages",
        "nav": [
          {
            "text": "指南",
            "link": "/zh/01.Guide"
          },
          {
            "text": "通知",
            "link": "/zh/02.Notification"
          },
          {
            "text": "邮件",
            "link": "/zh/03.Mails"
          },
          {
            "text": "办公软件",
            "link": "/zh/Office/",
            "items": [
              {
                "text": "Excel",
                "link": "/zh/Office/Excel/"
              },
              {
                "text": "PowerPoint",
                "link": "/zh/office/ppt/"
              },
              {
                "text": "Winword",
                "link": "/zh/Office/Word/"
              }
            ]
          },
          {
            "text": "系统",
            "link": "/zh/05.Windows/"
          }
        ],
        "sidebar": {}
      },
      "/en/": {
        "selectText": "Languages",
        "label": "English",
        "ariaLabel": "Languages",
        "nav": [
          {
            "text": "Guide",
            "link": "/en/Guide"
          },
          {
            "text": "Notification",
            "link": "/zh/Notification"
          },
          {
            "text": "GWS",
            "link": "/en/Mails"
          },
          {
            "text": "Office",
            "items": [
              {
                "text": "Excel",
                "link": "/en/04.Office/Excel/"
              },
              {
                "text": "PowerPoint",
                "link": "/pages/340ab6"
              },
              {
                "text": "Winword",
                "link": "/en/04.Office/Word/"
              }
            ]
          },
          {
            "text": "Windows",
            "link": "/en/05.Windows/"
          }
        ]
      }
    },
    "footer": {
      "createYear": 2023,
      "copyrightInfo": "Mitsumi"
    }
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "title": "Mitsumi",
      "description": "信息发布平台",
      "path": "/"
    },
    "/en/": {
      "lang": "en-US",
      "title": "Mitsumi",
      "description": "information publishing platform",
      "path": "/en/"
    }
  }
}